- name: Server-1
  glances_api_url: http://192.168.1.211:61208/api/3/
- name: Server-2
  glances_api_url: http://192.168.1.212:61208/api/3/
- name: Server-3
  glances_api_url: http://192.168.1.213:61208/api/4/
